import {
  Cosmetics,
  FoodApp,
  ContactApp,
  PortfolioEn,
  PortfolioFa,
  TravelApp,
  ChatApp,
  Weblog,
  Crypto,
} from "../assets/images/works";

export const works = [
  {
    title: "اپ رستوران",
    image: FoodApp,
    demo: "https://food-app-with-react-and-tailwind.netlify.app/",
    code: "https://github.com/babaei-mostafa/food-app",
    des: "فقط فرانت‌اند و هوم‌پیج است که با ReactJS و Tailwind نوشته شده است",
  },
  {
    title: "اپلیکیشن مخاطبین",
    image: ContactApp,
    demo: "https://spontaneous-monstera-94b1f7.netlify.app/",
    code: "https://github.com/babaei-mostafa/contacts-manager-app",
    des: "یک اپلیکیشن ذخیره مخاطبین است که با React و Bootstrap نوشته شده است و دیتا از سرور دریافت می‌شود و عملیات چهارگانه CRUD را دارد",
  },
  {
    title: "اپ کلینیک زیبایی",
    image: Cosmetics,
    demo: "https://cosmetics-english.vercel.app/",
    code: "https://github.com/babaei-mostafa/cosmetics-en",
    des: "یک وب‌اپلیکیشن که بک‌اند آن Headless Wordpress و فرانت‌اند آن NextJS است",
  },
  {
    title: "پرتفولیو انگلیسی",
    image: PortfolioEn,
    demo: "https://the-portfolio-app.netlify.app/",
    code: "https://github.com/babaei-mostafa/portfolio",
    des: "یک Portfolio‌به زبان انگلیسی است که با ReactJS و Tailwind نوشته شده است",
  },
  {
    title: "پرتفولیو فارسی",
    image: PortfolioFa,
    demo: "",
    code: "https://github.com/babaei-mostafa/portfolio-mui",
    des: "یک Portfolio‌ به زبان فارسی که با ReactJS و MaterialUI نوشته شده است",
  },
  {
    title: "اپ کریپتو",
    image: Crypto,
    demo: "https://preeminent-fairy-b34ac4.netlify.app/",
    code: "https://github.com/babaei-mostafa/crypto-app",
    des: "یک اپلیکیشن که دیتا را از یک API به‌نام coin Gecko می‌گیرد و نمایش می‌دهد. این اپلیکیشن با ReactJS و Tailwind نوشته شده است.",
  },
  {
    title: "اپ آژانس مسافرتی",
    image: TravelApp,
    demo: "https://travel-website-with-react-and-tailwind.netlify.app/",
    code: "https://github.com/babaei-mostafa/travel-website",
    des: "هوم‌پیج آژانس مسافرتی که با ReactJS و Tailwind نوشته شده است",
  },
  {
    title: "اپلیکیشن چت",
    image: ChatApp,
    demo: "https://the-chat-application.netlify.app/",
    code: "https://github.com/babaei-mostafa/chat-app",
    des: "یک اپلیکیشن برای چت است که با ReactJS و Firebase نوشته شده است",
  },
  {
    title: "اپلیکیشن وبلاگ",
    image: Weblog,
    demo: "https://weblog-application.netlify.app/",
    code: "https://github.com/babaei-mostafa/Weblog",
    des: "هوم‌پیج یک وبلاگ نوشته‌شده با ReactJS و Plain CSS",
  },
];
